### PR TITLE
Upgrades to SDK 50

### PR DESCRIPTION
**Pull request by jonsamp**
Ran:

`yarn add expo@next` and `npx expo install --fix`

### CODE REVIEW

**Comment by jonsamp** [comment]
When trying to run this in Expo Go, I get this error in the terminal:

```bash
TypeError: _configPlugins.Updates.getRuntimeVersionAsync is not a function
```

**Comment by jonsamp** [comment]
In Expo Go, I get this warning. After navigating to a new screen, I get a fatal error due to a reanimated method not being found.

Screenshot 2023-12-12 at 11 47 47 PM

**Comment by jonsamp** [comment]
Kicking off a new development build to see if I can get it running there.

**Comment by jonsamp** [comment]
Kicking off a production build. My ultimate goal is to send an update to make sure that works with real users.

**Comment by brentvatne** [comment]
> The error is happening because `global._REANIMATED_VERSION_CPP` appears to be incorrect, which reanimated uses to make sure the JS and native parts align. The cpp version is `undefined`, and the JS version is `3.6.1`. Since those don't match, I get the warning.

do you know how we could reproduce this to investigate further?

**Comment by jonsamp** [comment]
> > The error is happening because `global._REANIMATED_VERSION_CPP` appears to be incorrect, which reanimated uses to make sure the JS and native parts align. The cpp version is `undefined`, and the JS version is `3.6.1`. Since those don't match, I get the warning.
> 
> do you know how we could reproduce this to investigate further?

@brentvatne I just tried to make a minimum repro and was unable to. I ran `npx create-expo-app@latest --template tabs@49`, then upgraded that to SDK 50, but the warning did not appear.

One thing I've run into on both upgrades is that I have to remove the `'expo-router/babel'` plugin in **bable.config.js**. Might be worth noting that in the release notes?

**Comment by jonsamp** [comment]
I don't have time right now, but this app uses SQLite. Excited to try the new `expo-sqlite` module.

**Comment by jonsamp** [comment]
Screenshot 2023-12-13 at 12 57 41 AM

This is a good sequence of emails

**Pull request merged**
